using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditorInternal;
using UnityEngine;

[InitializeOnLoad]
public static class LayerScriptGenerator
{
    public const string enumName = "Layer";
    public const string extension = ".cs";
    public const string targetFolderPath = "Scripts/GameControl";

    private static string currentFileContent = "";
    private static string pathToTargetFolder = "";

    private static string FilePath => Path.Combine(pathToTargetFolder, enumName + extension);

    [MenuItem("Assets/Create/GameManagement/LayersFile", priority = -20)]
    private static void CreateAndUpdateLayersFile()
    {
        if (TryGetPathToTargetFolder() && !string.IsNullOrEmpty(pathToTargetFolder) && File.Exists(FilePath))
        {
            Debug.LogWarning("Layers file already exists");
            Update();
            return;
        }

        Directory.CreateDirectory(Path.Combine(Application.dataPath, targetFolderPath));
        File.Create(Path.Combine(Application.dataPath, targetFolderPath, enumName + extension));
        Update();
    }

    static LayerScriptGenerator()
    {
        //initialization of static fields in update because they are reset on domain reload and editor update callback isn't
        //there can be a situation where update is called and fields have default value
        EditorApplication.update += Update;
    }

    private static void Update()
    {
        if (!TryGetPathToTargetFolder() || string.IsNullOrEmpty(pathToTargetFolder))
        {
            return;
        }

        if (string.IsNullOrEmpty(currentFileContent))
        {
            TryGetCurrentFileContent();
        }

        string newFileContent = GetNewFileContent();
        if (newFileContent != currentFileContent)
        {
            currentFileContent = newFileContent;
            File.WriteAllText(FilePath, currentFileContent);

            //force unity to reimport this script so it recompiles it and doesn't throw warnings that "the file has been modified and unity doesn't know when"
            AssetDatabase.ImportAsset(Path.Combine("Assets", targetFolderPath, enumName + extension));
        }
    }

    private static bool TryGetPathToTargetFolder()
    {
        pathToTargetFolder = Directory.GetDirectories(Application.dataPath, targetFolderPath).FirstOrDefault();
        return !string.IsNullOrEmpty(pathToTargetFolder);
    }

    private static bool TryGetCurrentFileContent()
    {
        string filePath = FilePath;
        if (File.Exists(filePath))
        {
            currentFileContent = File.ReadAllText(filePath);
            return true;
        }
        return false;
    }

    private static string GetNewFileContent()
    {
        string[] layers = InternalEditorUtility.layers;

        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.AppendLine($"//Script generated by {nameof(LayerScriptGenerator)}.cs");
        stringBuilder.AppendLine($"public enum {enumName}");
        stringBuilder.AppendLine("{");

        int i = 0;
        foreach (string layer in layers)
        {
            string fieldName = ClearSpecialCharacters(layer);
            stringBuilder.AppendLine($"\t{fieldName} = {LayerMask.NameToLayer(layer)},");
            i++;
        }

        stringBuilder.AppendLine("}");

        stringBuilder.AppendLine("");

        stringBuilder.AppendLine($"public static class {enumName}Extensions");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"\tpublic static int GetLayerIndex(this {enumName} value)");
        stringBuilder.AppendLine("\t{");
        stringBuilder.AppendLine("\t\treturn (int)value;");
        stringBuilder.AppendLine("\t}");
        stringBuilder.AppendLine("}");

        return stringBuilder.ToString();
    }

    private static string ClearSpecialCharacters(string str)
    {
        string pattern = "[^a-zA-Z0-9]";
        string replacement = "_";
        return Regex.Replace(str, pattern, replacement);
    }
}
