using System.IO;
using System.Text;
using UnityEditor;

namespace StorkStudios.CoreNest
{
    [InitializeOnLoad]
    public static class SceneScriptGenerator
    {
        private class ScriptGenerator : ScriptGeneratorBase
        {
            public ScriptGenerator(string name, string assetPath, string extension = ".cs") : base(name, assetPath, extension) { }

            protected override string GetNewFileContent()
            {
                EditorBuildSettingsScene[] scenes = EditorBuildSettings.scenes;

                IndentedStringBuilder builder = new IndentedStringBuilder(new StringBuilder(), "\t");
                builder.AppendLine($"//Script generated by {nameof(SceneScriptGenerator)}.cs");
                builder.AppendLine("");
                builder.AppendLine("namespace StorkStudios.CoreNest");
                using (builder.BeginIndentScope(1, "{", "}"))
                {
                    builder.AppendLine($"public enum {name}");
                    using (builder.BeginIndentScope(1, "{", "}"))
                    {
                        int i = 0;
                        foreach (EditorBuildSettingsScene scene in scenes)
                        {
                            string sceneName = Path.GetFileNameWithoutExtension(scene.path);
                            string fieldName = ReplaceSpecialCharacters(sceneName);
                            builder.AppendLine($"{fieldName} = {i},");
                            i++;
                        }
                    }

                    builder.AppendLine("");

                    builder.AppendLine($"public static class {name}Extensions");
                    using (builder.BeginIndentScope(1, "{", "}"))
                    {
                        builder.AppendLine($"public static int GetBuildIndex(this {name} value)");
                        using (builder.BeginIndentScope(1, "{", "}"))
                        {
                            builder.AppendLine("return (int)value;");
                        }
                    }
                }
                return builder.ToString();
            }
        }

        private readonly static ScriptGenerator generator;

        [MenuItem("Assets/Create/GameControl/ScenesFile", priority = -20)]
        private static void CreateAndUpdateScenesFile()
        {
            generator.CreateAndUpdateFile();
        }

        static SceneScriptGenerator()
        {
            generator ??= new ScriptGenerator("Scene", "Scripts/GameControl");

            EditorBuildSettings.sceneListChanged += generator.UpdateFile;
        }
    }
}