//Script generated by SceneScriptGenerator.cs
public enum Scene
{
	SampleScene = 0,
	New_Scene = 1,
	New_Scene_1 = 2,
}

public static class SceneExtensions
{
	public static int GetBuildIndex(this Scene value)
	{
		return (int)value;
	}
}
