<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<PackageScribanIncludeSource>true</PackageScribanIncludeSource>
		<RootNamespace>StorkStudios.CoreNest.CodeAnalyzer</RootNamespace>
		<DefineConstants>SCRIBAN_PUBLIC</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference ExcludeAssets="runtime" Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0" />
		<PackageReference ExcludeAssets="runtime" Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.3.0" />

		<PackageReference IncludeAssets="Build" Include="Scriban" Version="6.5.0" />

		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
		<PackageReference Include="PolySharp" Version="1.15.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>

		<EmbeddedResource Include="**\*.sbncs" />
	</ItemGroup>
	
	<Target Name="CopyAfterBuild" BeforeTargets="Build">
		<ItemGroup>
			<_FilesToCopy Include="$(OutputPath)\$(AssemblyName).dll" />
			<_FilesToCopy Include="$(OutputPath)\$(AssemblyName).pdb" />
		</ItemGroup>
		<Copy SourceFiles="@(_FilesToCopy)" DestinationFolder="$(SolutionDir).." />
	</Target>

</Project>
